/**
 * Sync active recurring expenses → egresos
 *
 * Rules:
 * - Each active recurring item generates ONE expense per period it falls in
 * - Expenses generated have a `recurringId` field linking back to the recurring item
 * - Expenses are identified by: recurringId + year + month (for monthly), or recurringId + year (for annual)
 * - Already-existing generated expenses are never duplicated
 * - Paused recurring items don't generate expenses for months while paused
 * - Manually edited amounts on a generated expense are preserved
 *
 * Frequencies and their trigger months (0-indexed):
 *   Mensual    → every month
 *   Bimestral  → months 0,2,4,6,8,10
 *   Trimestral → months 0,3,6,9
 *   Semestral  → months 0,6
 *   Anual      → month 0 (January)
 */

const FREQ_MONTHS = {
  Mensual:    [0,1,2,3,4,5,6,7,8,9,10,11],
  Bimestral:  [0,2,4,6,8,10],
  Trimestral: [0,3,6,9],
  Semestral:  [0,6],
  Anual:      [0],
}

/**
 * Returns true if the recurring item should fire in the given month/year.
 */
function shouldFire(rec, month, year) {
  const allowed = FREQ_MONTHS[rec.freq] || FREQ_MONTHS['Mensual']
  return allowed.includes(month)
}

/**
 * Builds the unique key used to identify a generated expense.
 * Stored as `obs` field prefix so it persists in localStorage.
 */
export function recurringKey(recurringId, year, month) {
  return `__rec:${recurringId}:${year}-${String(month).padStart(2,'0')}`
}

/**
 * Given the full list of recurring items and existing expenses,
 * returns an array of NEW expense objects that need to be created.
 *
 * @param {Array} recurring  - all recurring items
 * @param {Array} expenses   - all existing expenses
 * @param {number} upToYear  - sync up to this year
 * @param {number} upToMonth - sync up to this month (0-indexed, inclusive)
 * @param {number} fromYear  - sync from this year (default 2026)
 * @param {number} fromMonth - sync from this month (default 0)
 */
export function computeMissingExpenses(recurring, expenses, upToYear, upToMonth, fromYear = 2026, fromMonth = 0) {
  // Build a set of existing generated-expense keys for fast lookup
  const existingKeys = new Set(
    expenses
      .filter(e => e.recurringId)
      .map(e => recurringKey(e.recurringId, ...parseRecKey(e)))
  )

  // Also check via obs field for backwards compat
  const existingObs = new Set(
    expenses
      .filter(e => e.obs && e.obs.startsWith('__rec:'))
      .map(e => e.obs.split('|')[0])
  )

  const toCreate = []

  for (const rec of recurring) {
    if (!rec.active) continue

    // Walk every month from fromYear/fromMonth to upToYear/upToMonth
    let y = fromYear, m = fromMonth
    while (y < upToYear || (y === upToYear && m <= upToMonth)) {
      if (shouldFire(rec, m, y)) {
        const key = recurringKey(rec.id, y, m)
        if (!existingKeys.has(key) && !existingObs.has(key)) {
          // Build date: year-month-day (use rec.day, capped to 28 to be safe)
          const day = Math.min(rec.day || 1, 28)
          const date = `${y}-${String(m + 1).padStart(2,'0')}-${String(day).padStart(2,'0')}`
          const MONTHS_ES = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']

          toCreate.push({
            id: `rec_${rec.id}_${y}_${m}`,
            date,
            cat: rec.cat,
            sub: rec.name,
            desc: `${rec.name} — ${MONTHS_ES[m]} ${y}`,
            provider: rec.name,
            amount: rec.amount,
            hasIVA: rec.hasIVA,
            ivaP: rec.ivaP,
            method: rec.method,
            obs: key,            // ← the link key
            recurringId: rec.id, // ← explicit FK
            autoGenerated: true,
          })
        }
      }
      // advance month
      m++
      if (m > 11) { m = 0; y++ }
    }
  }

  return toCreate
}

/** Extract year and month from a generated expense's obs or recurringId */
function parseRecKey(expense) {
  // key format: __rec:{id}:{year}-{mm}
  const obs = expense.obs || ''
  const match = obs.match(/__rec:[^:]+:(\d{4})-(\d{2})/)
  if (match) return [parseInt(match[1]), parseInt(match[2])]
  // fallback: parse from date
  if (expense.date) {
    const [y, m] = expense.date.split('-').map(Number)
    return [y, m - 1]
  }
  return [2026, 0]
}
